project:
  type: book

execute:
  freeze: auto

lang: pt
book:
  title: "Introdução à acessibilidade urbana"
  subtitle: "um guia prático em R"
  date: today
  status: "forthcoming"
  language: pt
  cover-image: images/cover.png
  site-url: https://ipeagit.github.io/intro_access_book/pt
  repo-url: https://github.com/ipeaGIT/intro_access_book 
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  favicon: images/favicon.png
  twitter-card: true
  open-graph: true
  google-analytics:
    tracking-id: "G-YVERJQF9PJ"
    anonymize-ip: true


  chapters:
    - index.qmd
    - part: s1_intro.qmd
      chapters:
        - 1_conceito.qmd
        - 2_indicadores.qmd
    - part: s2_calculo.qmd
      chapters:
        - 3_calculando_acesso.qmd
    - part: s3_dados_tp.qmd
      chapters:
        - 4_dados_gtfs.qmd
        - 5_gtfstools.qmd
    - part: s4_avaliacao_impacto.qmd
      chapters:
        - 6_cenarios_transporte.qmd
    - part: s5_dados_aop.qmd
      chapters:
        - 7_aopdata_populacao.qmd
        - 8_aopdata_uso_solo.qmd
        - 9_aopdata_acessibilidade.qmd
    - references.qmd

  page-navigation: true
  page-footer: 
    border: false
    left: "Copyright 2023, Ipea - Instituto de Pesquisa Econômica Aplicada" 
    right: 
      - icon: github
        href: https://github.com/ipeaGIT/intro_access_book

  sidebar:
    tools:
      - icon: download
        href: https://repositorio.ipea.gov.br/bitstream/11058/12264/1/Introducao_a_acessibilidade_urbana.pdf
        text: "Download PDF"

bibliography: references.bib

fig-dpi: 300

editor_options:
  markdown:
    wrap: 80
    canonical: true

theme:
  light: cosmo
  dark: superhero
  
crossref:
  fig-title: Figura
  fig-prefix: Figura
  tbl-title: Tabela
  tbl-prefix: Tabela
  sec-prefix: Seção

citation:
  type: book
  title: "Introdução à acessibilidade urbana: um guia prático em R"
  url: https://ipeagit.github.io/intro_access_book/pt
  publisher: "Ipea - Instituto de Pesquisa Econômica Aplicada"
  edition: 1
  issued: 2023
  abstract: "O objetivo deste livro é apresentar os conceitos e habilidades práticas necessárias para fazer estudos e avaliações de impacto de acessibilidade urbana. O livro começa dando uma visão geral sobre o conceito e os principais indicadores de acessibilidade. Em seguida, ensina como analisar dados espaciais e de redes de transporte para estimar níveis de acessibilidade por diferentes modos de transporte e como visualizar os resultados em forma de mapas e gráficos. O livro também familiariza o leitor com dados de redes de transporte público em formato GTFS e ensina como manipular e visualizar esse tipo de dado. Num dos seus principais capítulos, o livro ensina também como os dados e a metodologia apresentados nos capítulos anteriores podem ser utilizados para avaliar o impacto de projetos de transporte sobre as condições de acesso a oportunidades da população. Por fim, o livro apresenta como baixar, analisar e visualizar estimativas de acessibilidade já calculadas para cidades brasileiras e disponibilizadas pela equipe do Projeto Acesso a Oportunidades, do Ipea."

google-scholar: true